### PR TITLE
MOLGW v2.A results

### PR DESCRIPTION
**Pull request by bruneval**
Michiel,
I have run several times the GW100 suite with MOLGW.
PBE or PBE0, TZVPP or QZVP, and x2c-coulomb-fitting or cc-pVQZ-RI

1. The results obtained with the x2c-coulomb-fitting auxiliary basis are kind of crapy, but you said you want them anyway, right?
2. The cc-pVQZ-RI auxiliary basis is not complete. I've made some reckless substitutions to complete it for Ti, Cu, K, and Rb. The details are in the remark of the json files.
I hope you'll include these results in the web site. Please let me know how the comparison TM vs MOLGW performs.
Cheers,
Fabien

### CODE REVIEW

**Comment by bruneval** [comment]
Hi Michiel,
Thank you for having merge my files.
I checked on your website. It looks like my PBE0 data are not properly
named when selecting them in the menus.
The PBE are fine.
I did not realized that most of the error between TM and MOLGW come from
BeO.
As we said 10 days ago, we do not select the same QP peak: I select the one
with the largest weight and you select the highest energy peak...

Thanks again for including my data.

Fabien

**Comment by setten** [comment]
thanks a lot for your data, and for actually using git to provide it. I'll
look into the PBE0 naming.
I'll also update the plots on the main website but I may wait until I also
have the Fiesta results so that I can do it in one go.


Michiel van Setten
mjvansetten@gmail.com


Op ma 27 mei 2019 om 17:11 schreef Fabien Bruneval <notifications@github.com

**Comment by bruneval** [comment]
Thank you for having merged my data.
Please don't let the PBE0 results mislabeled for too long.
Hopefully, the Fiesta results will arrive soon.
Fabien

**Comment by setten** [comment]
Thanks for the new set, I merged and added it to the selections. the PBE0
names are also fixed now
Cheers,

Michiel van Setten
mjvansetten@gmail.com


Op di 28 mei 2019 om 10:35 schreef Fabien Bruneval <notifications@github.com

**Comment by bruneval** [comment]
Great! I feel better now that the PBE0 data are right!
See you soon.
Fabien

**Pull request merged**
